### PR TITLE
Fix migrator; move up to 2.0.7post1

### PR DESCRIPTION
**Pull request by jayfurmanek**
closes #5 
closes #4 

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is needed because `ecos-2.0.7.tar.gz` is no longer hosted on files.pythonhosted.org, only the post1 version is there now.

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@isuruf Is there a way to drop py2.7 just for aarch64 and ppc64le? The dependencies there are behind and probably always will be.

**Comment by isuruf** [comment]
Sure. `skip: True  # [py27 and (ppc64le or aarch64)]`

**Comment by jakirkham** [comment]
Followed by a re-render 😉

**Comment by jayfurmanek** [comment]
Right! I was trying to think of ways in conda-forge.yaml, but that makes more sense. Thanks!

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@dougalsutherland FYI

**Comment by jayfurmanek** [comment]
@dougalsutherland Friendly nudge

**Comment by jakirkham** [comment]
Thanks @jayfurmanek!

**Pull request merged**
