### PR TITLE
Build for windows

### LINKED ISSUE #1: Windows build
From https://github.com/conda-forge/staged-recipes/pull/6079; failed build [here](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.25470):
```
    ecos/src/ecos.c(1093): error C2065: '_TWO_DIGIT_EXPONENT': undeclared identifier
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2
```

### PR DESCRIPTION
**Pull request by h-vetinari**
Attempt to fix #1.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by h-vetinari** [comment]
@dougalsutherland, that was pleasantly painless! :)

**Comment by h-vetinari** [comment]
@dougalsutherland 
This is green - could you please merge it? :)

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge/core, I pinged the maintainer twice over more than a week on an all-green PR with no response. Have now added myself to maintainers, which is what @scopatz usually asked me to do for merging similar PRs for other repos.

Please merge if you're happy with that. :)

**Comment by scopatz** [comment]
I am pretty sure @dougalsutherland won't mind

**Comment by scopatz** [comment]
Thanks @h-vetinari!

**Pull request merged**
